/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import main.DistanceFinder;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        DistanceFinder classUnderTest = new DistanceFinder();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
